baseURL = ''
languageCode = 'nb-NO'
title = 'Buene Røyr og Maskin'

theme = 'boilerplate-hugo-theme'

[imaging]
  anchor = 'Smart'
  hint = 'photo'
  quality = 80
  resampleFilter = 'MitchellNetravali'

[Params]
  logo = 'logo.png'
  keywords = ['rørlegger', 'lærdal', 'årdal', 'aurland', 'utleie', 'minigraver']